propagate ctwm changes to vtwm and twm

diff --git a/twm/config.in b/twm/config.in
--- a/twm/config.in
+++ b/twm/config.in
@@ -7,7 +7,7 @@ prog=$(echo "$prog"|sed 's,^.*/,,')
 
 export TWM_TYPE=${1:-${TWM_TYPE:-twm}}
 if [ ! -x "`which $TWM_TYPE 2>/dev/null`" ]; then
-    echo "ERROR: cannot find usable twm program" >&2
+    echo "ERROR: cannot find usable $TWM_TYPE program" >&2
     exit 1;
 fi
 if [ -z "$TWM_VERSION" ]; then
diff --git a/vtwm/config.in b/vtwm/config.in
--- a/vtwm/config.in
+++ b/vtwm/config.in
@@ -7,7 +7,7 @@ prog=$(echo "$prog"|sed 's,^.*/,,')
 
 export VTWM_TYPE=${1:-${VTWM_TYPE:-vtwm}}
 if [ ! -x "`which $VTWM_TYPE 2>/dev/null`" ]; then
-    echo "ERROR: cannot find usable vtwm program" >&2
+    echo "ERROR: cannot find usable $VTWM_TYPE program" >&2
     exit 1;
 fi
 if [ -z "$VTWM_VERSION" ]; then
