more jwm workup

diff --git a/ctwm/config.in b/ctwm/config.in
--- a/ctwm/config.in
+++ b/ctwm/config.in
@@ -7,7 +7,7 @@ prog=$(echo "$prog"|sed 's,^.*/,,')
 
 export CTWM_TYPE=${1:-${CTWM_TYPE:-ctwm}}
 if [ ! -x "`which $CTWM_TYPE 2>/dev/null`" ]; then
-    echo "ERROR: cannot find usable ctwm program" >&2
+    echo "ERROR: cannot find usable $CTWM_TYPE program" >&2
     exit 1;
 fi
 if [ -z "$CTWM_VERSION" ]; then
@@ -20,31 +20,28 @@ fi
 export CTWM_VERSION=${2:-$CTWM_VERSION}
 export CTWM_CONFIG_HOME=${CTWM_CONFIG_HOME:-${HOME:-~}/.$CTWM_TYPE}
 export CTWM_CONFIG_SDIR=${CTWM_CONFIG_SDIR:-@sharedir@/$CTWM_TYPE}
+export CTWM_RCFILE="${3:-${CTWM_RCFILE:-$CTWM_CONFIG_HOME/rc}}"
 
-config() {
-    rcfile="$CTWM_CONFIG_HOME/rc.m4"
-    [ -s "$rcfile" ] || rcfile="$CTWM_CONFIG_SDIR/rc.m4"
-    [ -s "$rcfile" ] || { echo "ERROR: missing file $rcfile" >&2; exit 1; }
+m4file="$CTWM_CONFIG_HOME/rc.m4"
+[ -s "$m4file" ] || m4file="$CTWM_CONFIG_SDIR/rc.m4"
+[ -s "$m4file" ] || { echo "ERROR: missing file $m4file" >&2; exit 1; }
 
-    USER=${LOGNAME:-$USER}
-    HOME=${HOME:-~}
+USER=${LOGNAME:-$USER}
+HOME=${HOME:-~}
 
-    WIDTH=$(xwininfo -root|grep 'Width:'|awk '{print$2}')
-    HEIGHT=$(xwininfo -root|grep 'Height:'|awk '{print$2}')
+WIDTH=$(xwininfo -root|grep 'Width:'|awk '{print$2}')
+HEIGHT=$(xwininfo -root|grep 'Height:'|awk '{print$2}')
 
-    CLASS=$(xwininfo -root|grep 'Visual Class:'|awk '{print$3}')
-    case "$CLASS" in
-    (*Color)    COLOR='Yes' ;;
-    (*)	    COLOR='No' ;;
-    esac
+CLASS=$(xwininfo -root|grep 'Visual Class:'|awk '{print$3}')
+case "$CLASS" in
+(*Color)    COLOR='Yes' ;;
+(*)	    COLOR='No' ;;
+esac
 
-    m4 -DUSER="$USER" -DHOME="$HOME" \
-       -DWIDTH="$WIDTH" -DHEIGHT="$HEIGHT" \
-       -DCLASS="$CLASS" -DCOLOR="$COLOR" \
-       -DTWM_TYPE="$CTWM_TYPE" -DTWM_VERSION="$CTWM_VERSION" \
-       "$rcfile"
-}
-
-config >"$CTWM_CONFIG_HOME/rc"
+m4 -DUSER="$USER" -DHOME="$HOME" \
+   -DWIDTH="$WIDTH" -DHEIGHT="$HEIGHT" \
+   -DCLASS="$CLASS" -DCOLOR="$COLOR" \
+   -DTWM_TYPE="$CTWM_TYPE" -DTWM_VERSION="$CTWM_VERSION" \
+   "$m4file" >"$CTWM_CONFIG_HOME/rc"
 
 # vim: sw=4
diff --git a/jwm/start.in b/jwm/start.in
--- a/jwm/start.in
+++ b/jwm/start.in
@@ -7,7 +7,7 @@ prog=$(echo "$prog"|sed 's,^.*/,,')
 
 export JWM_TYPE=${1:-${JWM_TYPE:-jwm}}
 if [ ! -x "`which $JWM_TYPE >/dev/null`" ]; then
-    echo "ERROR: cannot find usable jwm program" >&2
+    echo "ERROR: cannot find usable $JWM_TYPE program" >&2
     exit 1;
 fi
 if [ -z "$JWM_VERSION" ]; then
@@ -24,7 +24,7 @@ export JWM_CONFIG_SDIR=${JWM_CONFIG_SDIR:-@shared@/$JWM_TYPE}
 [ -d "$JWM_CONFIG_HOME" ] || mkdir -p "$JWM_CONFIG_HOME"
 if [ -s "$JWM_CONFIG_SDIR/version" ]; then
     if [ ! -s "$JWM_CONFIG_HOME/version" -o ! diff "$JWM_CONFIG_SDIR/version" "$JWM_CONFIG_HOME/version" ] ; then
-	for file in config desktop groups keys menu rc root tray; do
+	for file in defaults desktop groups keys menu rc root tray; do
 	    if [ ! -f "$JWM_CONFIG_SDIR/$file" -o ! diff "$JWM_CONFIG_SDIR/$file" "$JWM_CONFIG_HOME/$file" ] ; then
 		[ ! -f "$JWM_CONFIG_HOME/$file" ] || /bin/mv -f "$JWM_CONFIG_HOME/$file" "$JWM_CONFIG_HOME/$file.bak"
 		cat "$JWM_CONFIG_SDIR/$file" \
@@ -32,6 +32,44 @@ if [ -s "$JWM_CONFIG_SDIR/version" ]; then
 		    >"$JWM_CONFIG_HOME/$file"
 	    fi
 	done
+	cat>"$JWM_CONFIG_HOME/paths"<<-JWMEOF
+	    <?xml version="1.0"?>
+	    <JWM>
+	       <IconPath>$JWM_CONFIG_HOME/icons</IconPath>
+	       <IconPath>$JWM_CONFIG_HOME/styles</IconPath>
+	       <IconPath>$JWM_CONFIG_HOME/themes</IconPath>
+	       <IconPath>$JWM_CONFIG_SDIR/icons</IconPath>
+	       <IconPath>$JWM_CONFIG_SDIR/styles</IconPath>
+	       <IconPath>$JWM_CONFIG_SDIR/themes</IconPath>
+	       <IconPath>/usr/share/icons/Mist/16x16/apps</IconPath>
+	       <IconPath>/usr/share/icons/hicolor/16x16/apps</IconPath>
+	       <IconPath>/usr/share/icons/gnome/16x16/apps</IconPath>
+	       <IconPath>/usr/share/pixmaps</IconPath>
+	       <IconPath>$HOME/.icons</IconPath>
+	    </JWM>
+JWMEOF
+	cat>"$JWM_CONFIG_HOME/rc"<<-JWMEOF
+	    <?xml version="1.0"?>
+	    <JWM>
+	       <Include>$JWM_CONFIG_HOME/root</Include>
+	       <Include>$JWM_CONFIG_HOME/groups</Include>
+	       <Include>$JWM_CONFIG_HOME/tray</Include>
+	       <Include>$JWM_CONFIG_HOME/style</Include>
+	       <Include>$JWM_CONFIG_HOME/desktop</Include>
+	       <Include>$JWM_CONFIG_HOME/defaults</Include>
+	       <Include>$JWM_CONFIG_HOME/paths</Include>
+	       <Include>$JWM_CONFIG_HOME/keys</Include>
+	    </JWM>
+JWMEOF
+	cat>"$JWM_CONFIG_HOME/root"<<-JWMEOF
+	    <?xml version="1.0"?>
+	    <JWM>
+	       <RootMenu height="16" onroot="13">
+	          <Include>$JWM_CONFIG_HOME/menu</Include>
+	       </RootMenu>
+	    </JWM>
+JWMEOF
+
     fi
 fi
 
diff --git a/twm/config.in b/twm/config.in
--- a/twm/config.in
+++ b/twm/config.in
@@ -16,31 +16,28 @@ fi
 export TWM_VERSION=${2:-$TWM_VERSION}
 export TWM_CONFIG_HOME=${TWM_CONFIG_HOME:-${HOME:-~}/.$TWM_TYPE}
 export TWM_CONFIG_SDIR=${TWM_CONFIG_SDIR:-@sharedir@/$TWM_TYPE}
+export TWM_RCFILE="${3:-${TWM_RCFILE:-$TWM_CONFIG_HOME/rc}}"
 
-config() {
-    rcfile="$TWM_CONFIG_HOME/rc.m4"
-    [ -s "$rcfile" ] || rcfile="$TWM_CONFIG_SDIR/rc.m4"
-    [ -s "$rcfile" ] || { echo "ERROR: missing file $rcfile" >&2; exit 1; }
+m4file="$TWM_CONFIG_HOME/rc.m4"
+[ -s "$m4file" ] || m4file="$TWM_CONFIG_SDIR/rc.m4"
+[ -s "$m4file" ] || { echo "ERROR: missing file $m4file" >&2; exit 1; }
 
-    USER=${LOGNAME:-$USER}
-    HOME=${HOME:-~}
+USER=${LOGNAME:-$USER}
+HOME=${HOME:-~}
 
-    WIDTH=$(xwininfo -root|grep 'Width:'|awk '{print$2}')
-    HEIGHT=$(xwininfo -root|grep 'Height:'|awk '{print$2}')
+WIDTH=$(xwininfo -root|grep 'Width:'|awk '{print$2}')
+HEIGHT=$(xwininfo -root|grep 'Height:'|awk '{print$2}')
 
-    CLASS=$(xwininfo -root|grep 'Visual Class:'|awk '{print$3}')
-    case "$CLASS" in
-    (*Color)    COLOR='Yes' ;;
-    (*)	    COLOR='No' ;;
-    esac
+CLASS=$(xwininfo -root|grep 'Visual Class:'|awk '{print$3}')
+case "$CLASS" in
+(*Color)    COLOR='Yes' ;;
+(*)	    COLOR='No' ;;
+esac
 
-    m4 -DUSER="$USER" -DHOME="$HOME" \
-       -DWIDTH="$WIDTH" -DHEIGHT="$HEIGHT" \
-       -DCLASS="$CLASS" -DCOLOR="$COLOR" \
-       -DTWM_TYPE="$TWM_TYPE" -DTWM_VERSION="$TWM_VERSION" \
-       "$rcfile"
-}
-
-config >"$TWM_CONFIG_HOME/rc"
+m4 -DUSER="$USER" -DHOME="$HOME" \
+   -DWIDTH="$WIDTH" -DHEIGHT="$HEIGHT" \
+   -DCLASS="$CLASS" -DCOLOR="$COLOR" \
+   -DTWM_TYPE="$TWM_TYPE" -DTWM_VERSION="$TWM_VERSION" \
+   "$m4file" >"$TWM_CONFIG_HOME/rc"
 
 # vim: sw=4
diff --git a/vtwm/config.in b/vtwm/config.in
--- a/vtwm/config.in
+++ b/vtwm/config.in
@@ -20,31 +20,28 @@ fi
 export VTWM_VERSION=${2:-$VTWM_VERSION}
 export VTWM_CONFIG_HOME=${VTWM_CONFIG_HOME:-${HOME:-~}/.$VTWM_TYPE}
 export VTWM_CONFIG_SDIR=${VTWM_CONFIG_SDIR:-@sharedir@/$VTWM_TYPE}
+export VTWM_RCFILE="${3:-${VTWM_RCFILE:-$VTWM_CONFIG_HOME/rc}}"
 
-config() {
-    rcfile="$VTWM_CONFIG_HOME/rc.m4"
-    [ -s "$rcfile" ] || rcfile="$VTWM_CONFIG_SDIR/rc.m4"
-    [ -s "$rcfile" ] || { echo "ERROR: missing file $rcfile" >&2; exit 1; }
+m4file="$VTWM_CONFIG_HOME/rc.m4"
+[ -s "$m4file" ] || m4file="$VTWM_CONFIG_SDIR/rc.m4"
+[ -s "$m4file" ] || { echo "ERROR: missing file $m4file" >&2; exit 1; }
 
-    USER=${LOGNAME:-$USER}
-    HOME=${HOME:-~}
+USER=${LOGNAME:-$USER}
+HOME=${HOME:-~}
 
-    WIDTH=$(xwininfo -root|grep 'Width:'|awk '{print$2}')
-    HEIGHT=$(xwininfo -root|grep 'Height:'|awk '{print$2}')
+WIDTH=$(xwininfo -root|grep 'Width:'|awk '{print$2}')
+HEIGHT=$(xwininfo -root|grep 'Height:'|awk '{print$2}')
 
-    CLASS=$(xwininfo -root|grep 'Visual Class:'|awk '{print$3}')
-    case "$CLASS" in
-    (*Color)    COLOR='Yes' ;;
-    (*)	    COLOR='No' ;;
-    esac
+CLASS=$(xwininfo -root|grep 'Visual Class:'|awk '{print$3}')
+case "$CLASS" in
+(*Color)    COLOR='Yes' ;;
+(*)	    COLOR='No' ;;
+esac
 
-    m4 -DUSER="$USER" -DHOME="$HOME" \
-       -DWIDTH="$WIDTH" -DHEIGHT="$HEIGHT" \
-       -DCLASS="$CLASS" -DCOLOR="$COLOR" \
-       -DTWM_TYPE="$VTWM_TYPE" -DTWM_VERSION="$VTWM_VERSION" \
-       "$rcfile"
-}
-
-config >"$VTWM_CONFIG_HOME/rc"
+m4 -DUSER="$USER" -DHOME="$HOME" \
+   -DWIDTH="$WIDTH" -DHEIGHT="$HEIGHT" \
+   -DCLASS="$CLASS" -DCOLOR="$COLOR" \
+   -DTWM_TYPE="$VTWM_TYPE" -DTWM_VERSION="$VTWM_VERSION" \
+   "$m4file" >"$VTWM_CONFIG_HOME/rc"
 
 # vim: sw=4
